apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  # no of pods that are running currently in deployment
  replicas: 1
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
      - name: client
        # image: stephengrider/multi-client
        image: meyash/multiple_workflow_client
        ports:
        - containerPort: 3000
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "while true; do sleep 30; done;" ]
